/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoCinema;

import javax.swing.JOptionPane;
import modeloConnection.ConexaoDB;
import modeloDao.DaoUsuario;
import modeloBeans.BeansUsuario;

/**
 *
 * @author backdoors
 */
public class CadastroUsuario extends javax.swing.JFrame {

    BeansUsuario modUsu = new BeansUsuario();
    DaoUsuario controlUsu = new DaoUsuario();
    ConexaoDB conect = new ConexaoDB();
    int flag =0;
    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jLabelSobrenomeUsuario = new javax.swing.JLabel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelSenha = new javax.swing.JLabel();
        jLabelConfirmaSenha = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelTelefone = new javax.swing.JLabel();
        jLabelCPF = new javax.swing.JLabel();
        jFormattedTextFieldCPF = new javax.swing.JFormattedTextField();
        jFormattedTextFieldNome = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSobrenome = new javax.swing.JFormattedTextField();
        jPasswordFieldSenha = new javax.swing.JPasswordField();
        jFormattedTextFieldLogin = new javax.swing.JFormattedTextField();
        jPasswordFieldConfirmaSenha = new javax.swing.JPasswordField();
        jFormattedTextFieldEmail = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jButtonVoltar = new javax.swing.JButton();
        jButtonGravar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonNovoUsuario = new javax.swing.JButton();
        jLabelCadastroDeUsuario = new javax.swing.JLabel();
        jLabelPesquisaPeloCpf = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jFormattedTextFieldPesquisa = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de usuário");

        jLabelNomeUsuario.setText("Nome:");

        jLabelSobrenomeUsuario.setText("Sobrenome:");

        jLabelLogin.setText("Login:");

        jLabelSenha.setText("Senha:");

        jLabelConfirmaSenha.setText("Confirma senha:");

        jLabelEmail.setText("E-mail:");

        jLabelTelefone.setText("Telefone:");

        jLabelCPF.setText("CPF:");

        jFormattedTextFieldCPF.setEnabled(false);

        jFormattedTextFieldNome.setEnabled(false);

        jFormattedTextFieldSobrenome.setEnabled(false);

        jPasswordFieldSenha.setEnabled(false);

        jFormattedTextFieldLogin.setEnabled(false);

        jPasswordFieldConfirmaSenha.setEnabled(false);
        jPasswordFieldConfirmaSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldConfirmaSenhaActionPerformed(evt);
            }
        });

        jFormattedTextFieldEmail.setEnabled(false);

        jFormattedTextFieldTelefone.setEnabled(false);

        jButtonVoltar.setText("Voltar");
        jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarActionPerformed(evt);
            }
        });

        jButtonGravar.setText("Gravar");
        jButtonGravar.setEnabled(false);
        jButtonGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGravarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonEditar.setText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonNovoUsuario.setText("Novo");
        jButtonNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoUsuarioActionPerformed(evt);
            }
        });

        jLabelCadastroDeUsuario.setText("Cadastro de usuário");
        jLabelCadastroDeUsuario.setVerifyInputWhenFocusTarget(false);

        jLabelPesquisaPeloCpf.setText("Pesquisar pelo CPF:");

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("ID:");

        jTextFieldID.setEnabled(false);
        jTextFieldID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelConfirmaSenha)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabelTelefone, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelLogin)
                                    .addComponent(jLabelSenha))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabelNomeUsuario)
                                        .addComponent(jLabelSobrenomeUsuario)
                                        .addComponent(jLabelCPF)
                                        .addComponent(jLabelPesquisaPeloCpf)
                                        .addComponent(jLabel1))
                                    .addGap(5, 5, 5)))
                            .addGap(3, 3, 3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldLogin, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldSobrenome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldNome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jFormattedTextFieldEmail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordFieldConfirmaSenha)
                                .addComponent(jFormattedTextFieldTelefone)
                                .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(4, 4, 4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jFormattedTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jButtonPesquisar)))))
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabelCadastroDeUsuario)
                            .addGap(197, 197, 197)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jButtonNovoUsuario)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEditar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonGravar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jButtonVoltar)
                        .addGap(34, 34, 34))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelCadastroDeUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPesquisaPeloCpf)
                    .addComponent(jButtonPesquisar)
                    .addComponent(jFormattedTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNomeUsuario)
                    .addComponent(jFormattedTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSobrenomeUsuario)
                    .addComponent(jFormattedTextFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPF)
                    .addComponent(jFormattedTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogin)
                    .addComponent(jFormattedTextFieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSenha)
                    .addComponent(jPasswordFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConfirmaSenha)
                    .addComponent(jPasswordFieldConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jFormattedTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTelefone)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVoltar)
                    .addComponent(jButtonGravar)
                    .addComponent(jButtonExcluir)
                    .addComponent(jButtonEditar)
                    .addComponent(jButtonNovoUsuario)
                    .addComponent(jButtonCancelar))
                .addGap(19, 19, 19))
        );

        setSize(new java.awt.Dimension(626, 552));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
        TelaPrincipal telaPrincipal = new TelaPrincipal();
        telaPrincipal.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonVoltarActionPerformed

    private void jPasswordFieldConfirmaSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldConfirmaSenhaActionPerformed
        
    }//GEN-LAST:event_jPasswordFieldConfirmaSenhaActionPerformed

    private void jButtonGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGravarActionPerformed
        
        if (jFormattedTextFieldNome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o nome do usuário!");
            jFormattedTextFieldNome.requestFocus();
        }else if(jFormattedTextFieldSobrenome.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o sobrenome do usuário!");
            jFormattedTextFieldSobrenome.requestFocus();
        }else if(jFormattedTextFieldCPF.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o CPF do usuário!");
            jFormattedTextFieldCPF.requestFocus();
        }else if(jFormattedTextFieldLogin.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o login do usuário!");
            jFormattedTextFieldLogin.requestFocus();
        }else if(jPasswordFieldSenha.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha a senha do usuário!");
            jPasswordFieldSenha.requestFocus();
        }else if(jFormattedTextFieldEmail.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o e-mail do usuário!");
            jFormattedTextFieldEmail.requestFocus();
        }else if(jFormattedTextFieldTelefone.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o telefone do usuário!");
            jFormattedTextFieldTelefone.requestFocus();
        }else{
            
            if (jPasswordFieldSenha.getText().equals(jPasswordFieldConfirmaSenha.getText())){
                if (flag==1){
                modUsu.setNome(jFormattedTextFieldNome.getText());
                modUsu.setSobrenome(jFormattedTextFieldSobrenome.getText());
                modUsu.setCpf(jFormattedTextFieldCPF.getText());
                modUsu.setLogin(jFormattedTextFieldLogin.getText());
                modUsu.setSenha(jPasswordFieldSenha.getText());
                modUsu.setEmail(jFormattedTextFieldEmail.getText());
                modUsu.setTelefone(jFormattedTextFieldTelefone.getText());
                controlUsu.Gravar(modUsu);

                jTextFieldID.setText("");
                jFormattedTextFieldNome.setText("");
                jFormattedTextFieldSobrenome.setText("");
                jFormattedTextFieldCPF.setText("");
                jFormattedTextFieldLogin.setText("");
                jPasswordFieldSenha.setText("");
                jPasswordFieldConfirmaSenha.setText("");
                jFormattedTextFieldEmail.setText("");
                jFormattedTextFieldTelefone.setText("");
                jFormattedTextFieldPesquisa.setText("");

                jFormattedTextFieldNome.setEnabled(!true);
                jFormattedTextFieldSobrenome.setEnabled(!true);
                jFormattedTextFieldCPF.setEnabled(!true);
                jFormattedTextFieldLogin.setEnabled(!true);
                jPasswordFieldSenha.setEnabled(!true);
                jPasswordFieldConfirmaSenha.setEnabled(!true);
                jFormattedTextFieldEmail.setEnabled(!true);
                jFormattedTextFieldTelefone.setEnabled(!true);
                jFormattedTextFieldPesquisa.setEnabled(!false);
                jButtonNovoUsuario.setEnabled(true);
                jButtonGravar.setEnabled(!true);
                jButtonPesquisar.setEnabled(true);        
                jButtonExcluir.setEnabled(false);
                jButtonEditar.setEnabled(false);
                jButtonCancelar.setEnabled(!true);


                }else{
                modUsu.setId(Integer.parseInt(jTextFieldID.getText()));
                modUsu.setNome(jFormattedTextFieldNome.getText());
                modUsu.setSobrenome(jFormattedTextFieldSobrenome.getText());
                modUsu.setCpf(jFormattedTextFieldCPF.getText());
                modUsu.setLogin(jFormattedTextFieldLogin.getText());
                modUsu.setSenha(jPasswordFieldSenha.getText());
                modUsu.setEmail(jFormattedTextFieldEmail.getText());
                modUsu.setTelefone(jFormattedTextFieldTelefone.getText());
                controlUsu.Editar(modUsu);

                jTextFieldID.setText("");
                jFormattedTextFieldNome.setText("");
                jFormattedTextFieldSobrenome.setText("");
                jFormattedTextFieldCPF.setText("");
                jFormattedTextFieldLogin.setText("");
                jPasswordFieldSenha.setText("");
                jPasswordFieldConfirmaSenha.setText("");
                jFormattedTextFieldEmail.setText("");
                jFormattedTextFieldTelefone.setText("");
                jFormattedTextFieldPesquisa.setText("");

                jFormattedTextFieldNome.setEnabled(!true);
                jFormattedTextFieldSobrenome.setEnabled(!true);
                jFormattedTextFieldCPF.setEnabled(!true);
                jFormattedTextFieldLogin.setEnabled(!true);
                jPasswordFieldSenha.setEnabled(!true);
                jPasswordFieldConfirmaSenha.setEnabled(!true);
                jFormattedTextFieldEmail.setEnabled(!true);
                jFormattedTextFieldTelefone.setEnabled(!true);
                jFormattedTextFieldPesquisa.setEnabled(!false);
                jButtonNovoUsuario.setEnabled(true);
                jButtonGravar.setEnabled(!true);
                jButtonPesquisar.setEnabled(true);        
                jButtonExcluir.setEnabled(false);
                jButtonEditar.setEnabled(false);
                jButtonCancelar.setEnabled(!true);
                }
            }else{
                JOptionPane.showMessageDialog(null,"As senhas devem ser iguais!");
            }
        }
    }//GEN-LAST:event_jButtonGravarActionPerformed

    private void jButtonNovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoUsuarioActionPerformed
        
        flag =1;    
        
        jFormattedTextFieldNome.setEnabled(true);
        jFormattedTextFieldSobrenome.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jFormattedTextFieldLogin.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldConfirmaSenha.setEnabled(true);
        jFormattedTextFieldEmail.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jButtonGravar.setEnabled(true);
        jButtonPesquisar.setEnabled(false);
        jFormattedTextFieldPesquisa.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        
    }//GEN-LAST:event_jButtonNovoUsuarioActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jFormattedTextFieldNome.setEnabled(!true);
        jFormattedTextFieldSobrenome.setEnabled(!true);
        jFormattedTextFieldCPF.setEnabled(!true);
        jFormattedTextFieldLogin.setEnabled(!true);
        jPasswordFieldSenha.setEnabled(!true);
        jPasswordFieldConfirmaSenha.setEnabled(!true);
        jFormattedTextFieldEmail.setEnabled(!true);
        jFormattedTextFieldTelefone.setEnabled(!true);
        jFormattedTextFieldPesquisa.setEnabled(!false);
        jButtonNovoUsuario.setEnabled(true);
        jButtonGravar.setEnabled(!true);
        jButtonPesquisar.setEnabled(true);        
        jButtonExcluir.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonCancelar.setEnabled(!true);
        
        jTextFieldID.setText("");
        jFormattedTextFieldNome.setText("");
        jFormattedTextFieldSobrenome.setText("");
        jFormattedTextFieldCPF.setText("");
        jFormattedTextFieldLogin.setText("");
        jPasswordFieldSenha.setText("");
        jPasswordFieldConfirmaSenha.setText("");
        jFormattedTextFieldEmail.setText("");
        jFormattedTextFieldTelefone.setText("");
        jFormattedTextFieldPesquisa.setText("");
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed

         if (jFormattedTextFieldPesquisa.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o CPF para pesquisar!");
            jFormattedTextFieldPesquisa.requestFocus();
         }else{
            modUsu.setPesquisa(jFormattedTextFieldPesquisa.getText());
            BeansUsuario modelo = controlUsu.buscaUsuario(modUsu);
            jTextFieldID.setText(String.valueOf(modelo.getId()));
            jFormattedTextFieldNome.setText(modelo.getNome());
            jFormattedTextFieldSobrenome.setText(modelo.getSobrenome());
            jFormattedTextFieldCPF.setText(modelo.getCpf());
            jFormattedTextFieldLogin.setText(modelo.getLogin());
            jPasswordFieldSenha.setText(modelo.getSenha());
            jPasswordFieldConfirmaSenha.setText(modelo.getSenha());
            jFormattedTextFieldEmail.setText(modelo.getEmail());
            jFormattedTextFieldTelefone.setText(modelo.getTelefone());
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);  
         }
        
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        flag =2;
        
        jFormattedTextFieldNome.setEnabled(true);
        jFormattedTextFieldSobrenome.setEnabled(true);
        jFormattedTextFieldCPF.setEnabled(true);
        jFormattedTextFieldLogin.setEnabled(true);
        jPasswordFieldSenha.setEnabled(true);
        jPasswordFieldConfirmaSenha.setEnabled(true);
        jFormattedTextFieldEmail.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jButtonGravar.setEnabled(true);
        jButtonPesquisar.setEnabled(false);
        jFormattedTextFieldPesquisa.setEnabled(false);
        jButtonCancelar.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonNovoUsuario.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTextFieldIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldIDActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        int temp =0;
        temp = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente excluir o usuário?");
        if (temp == JOptionPane.YES_OPTION){
            modUsu.setId(Integer.parseInt(jTextFieldID.getText()));
            controlUsu.Excluir(modUsu);
            jFormattedTextFieldNome.setEnabled(!true);
            jFormattedTextFieldSobrenome.setEnabled(!true);
            jFormattedTextFieldCPF.setEnabled(!true);
            jFormattedTextFieldLogin.setEnabled(!true);
            jPasswordFieldSenha.setEnabled(!true);
            jPasswordFieldConfirmaSenha.setEnabled(!true);
            jFormattedTextFieldEmail.setEnabled(!true);
            jFormattedTextFieldTelefone.setEnabled(!true);
            jFormattedTextFieldPesquisa.setEnabled(!false);
            jButtonNovoUsuario.setEnabled(true);
            jButtonGravar.setEnabled(!true);
            jButtonPesquisar.setEnabled(true);        
            jButtonExcluir.setEnabled(false);
            jButtonEditar.setEnabled(false);
            jButtonCancelar.setEnabled(!true);
            jTextFieldID.setText("");
            jFormattedTextFieldNome.setText("");
            jFormattedTextFieldSobrenome.setText("");
            jFormattedTextFieldCPF.setText("");
            jFormattedTextFieldLogin.setText("");
            jPasswordFieldSenha.setText("");
            jPasswordFieldConfirmaSenha.setText("");
            jFormattedTextFieldEmail.setText("");
            jFormattedTextFieldTelefone.setText("");
            jFormattedTextFieldPesquisa.setText("");
        }
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }
    
    public String nome;
    public String sobrenome;
    public String senha;
    public String confirmaSenha;
    public String email;
    public String telefone;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonGravar;
    private javax.swing.JButton jButtonNovoUsuario;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonVoltar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFormattedTextField jFormattedTextFieldCPF;
    private javax.swing.JFormattedTextField jFormattedTextFieldEmail;
    private javax.swing.JFormattedTextField jFormattedTextFieldLogin;
    private javax.swing.JFormattedTextField jFormattedTextFieldNome;
    private javax.swing.JFormattedTextField jFormattedTextFieldPesquisa;
    private javax.swing.JFormattedTextField jFormattedTextFieldSobrenome;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCadastroDeUsuario;
    private javax.swing.JLabel jLabelConfirmaSenha;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JLabel jLabelPesquisaPeloCpf;
    private javax.swing.JLabel jLabelSenha;
    private javax.swing.JLabel jLabelSobrenomeUsuario;
    private javax.swing.JLabel jLabelTelefone;
    private javax.swing.JPasswordField jPasswordFieldConfirmaSenha;
    private javax.swing.JPasswordField jPasswordFieldSenha;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables
}
