/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProjetoCinema;

import javax.swing.JButton;

/**
 *
 * @author backdoors
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jLabelFilmes = new javax.swing.JLabel();
        jButton127horas = new javax.swing.JButton();
        jButtonAHospedeira = new javax.swing.JButton();
        jButtonFastNFurious = new javax.swing.JButton();
        jButtonMeuNomeNaoEJhonny = new javax.swing.JButton();
        jButtonStarWars = new javax.swing.JButton();
        jButtonTheDarkKnight = new javax.swing.JButton();
        jMenuBarMenuGeral = new javax.swing.JMenuBar();
        jMenuMenu = new javax.swing.JMenu();
        jMenuItemMenuPrincipal = new javax.swing.JMenuItem();
        jMenuItemCadastrarUsuario = new javax.swing.JMenuItem();
        jMenuItemTrocarUsuario = new javax.swing.JMenuItem();
        jMenuRelatorio = new javax.swing.JMenu();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tela principal");

        jInternalFrame1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jInternalFrame1.setClosable(true);
        jInternalFrame1.setTitle("Compra de ingressos");
        jInternalFrame1.setToolTipText("");
        jInternalFrame1.setVisible(true);
        jInternalFrame1.getContentPane().setLayout(null);

        jLabelFilmes.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabelFilmes.setText("Filmes:");
        jInternalFrame1.getContentPane().add(jLabelFilmes);
        jLabelFilmes.setBounds(240, 0, 70, 21);

        jButton127horas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/123horas.jpg"))); // NOI18N
        jButton127horas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton127horasActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButton127horas);
        jButton127horas.setBounds(10, 30, 150, 230);

        jButtonAHospedeira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/aHospedeira.jpg"))); // NOI18N
        jButtonAHospedeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAHospedeiraActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonAHospedeira);
        jButtonAHospedeira.setBounds(220, 30, 150, 230);

        jButtonFastNFurious.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/fastNFurious.jpg"))); // NOI18N
        jButtonFastNFurious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFastNFuriousActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonFastNFurious);
        jButtonFastNFurious.setBounds(410, 30, 150, 230);

        jButtonMeuNomeNaoEJhonny.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/meuNomeNaoEJohnny.jpg"))); // NOI18N
        jButtonMeuNomeNaoEJhonny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeuNomeNaoEJhonnyActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonMeuNomeNaoEJhonny);
        jButtonMeuNomeNaoEJhonny.setBounds(10, 300, 150, 230);

        jButtonStarWars.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/starWars.jpg"))); // NOI18N
        jButtonStarWars.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonStarWarsActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonStarWars);
        jButtonStarWars.setBounds(220, 300, 150, 230);

        jButtonTheDarkKnight.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/theDarkKnight.jpg"))); // NOI18N
        jButtonTheDarkKnight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTheDarkKnightActionPerformed(evt);
            }
        });
        jInternalFrame1.getContentPane().add(jButtonTheDarkKnight);
        jButtonTheDarkKnight.setBounds(410, 300, 150, 230);

        jMenuMenu.setText("Menu");

        jMenuItemMenuPrincipal.setText("Compra de ingressos");
        jMenuItemMenuPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMenuPrincipalActionPerformed(evt);
            }
        });
        jMenuMenu.add(jMenuItemMenuPrincipal);

        jMenuItemCadastrarUsuario.setText("Cadastrar usuário");
        jMenuItemCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastrarUsuarioActionPerformed(evt);
            }
        });
        jMenuMenu.add(jMenuItemCadastrarUsuario);

        jMenuItemTrocarUsuario.setText("Trocar de usuário");
        jMenuItemTrocarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTrocarUsuarioActionPerformed(evt);
            }
        });
        jMenuMenu.add(jMenuItemTrocarUsuario);

        jMenuBarMenuGeral.add(jMenuMenu);

        jMenuRelatorio.setText("Relatório");
        jMenuBarMenuGeral.add(jMenuRelatorio);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair do sistema");
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBarMenuGeral.add(jMenuSair);

        setJMenuBar(jMenuBarMenuGeral);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 569, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.DEFAULT_SIZE, 562, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(603, 625));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemTrocarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTrocarUsuarioActionPerformed
        Login login = new Login();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemTrocarUsuarioActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemMenuPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMenuPrincipalActionPerformed
        TelaPrincipal tela = new TelaPrincipal();
        tela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItemMenuPrincipalActionPerformed

    private void jButton127horasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton127horasActionPerformed
        DetalhesFilme detalhesFilme = new DetalhesFilme();  
        detalhesFilme.recebeFoto(this.jButton127horas.getIcon());
        detalhesFilme.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton127horasActionPerformed

    private void jButtonAHospedeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAHospedeiraActionPerformed
        DetalhesFilme detalhesFilme = new DetalhesFilme();  
        detalhesFilme.recebeFoto(this.jButtonAHospedeira.getIcon());
        detalhesFilme.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonAHospedeiraActionPerformed

    private void jButtonFastNFuriousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFastNFuriousActionPerformed
        DetalhesFilme detalhesFilme = new DetalhesFilme();  
        detalhesFilme.recebeFoto(this.jButtonFastNFurious.getIcon());
        detalhesFilme.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonFastNFuriousActionPerformed

    private void jButtonMeuNomeNaoEJhonnyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeuNomeNaoEJhonnyActionPerformed
        DetalhesFilme detalhesFilme = new DetalhesFilme();  
        detalhesFilme.recebeFoto(this.jButtonMeuNomeNaoEJhonny.getIcon());
        detalhesFilme.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonMeuNomeNaoEJhonnyActionPerformed

    private void jButtonStarWarsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonStarWarsActionPerformed
        DetalhesFilme detalhesFilme = new DetalhesFilme();  
        detalhesFilme.recebeFoto(this.jButtonStarWars.getIcon());
        detalhesFilme.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonStarWarsActionPerformed

    private void jButtonTheDarkKnightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTheDarkKnightActionPerformed
        DetalhesFilme detalhesFilme = new DetalhesFilme();  
        detalhesFilme.recebeFoto(this.jButtonTheDarkKnight.getIcon());
        detalhesFilme.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonTheDarkKnightActionPerformed

    private void jMenuItemCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastrarUsuarioActionPerformed
        CadastroUsuario cadastroUsuario = new CadastroUsuario();
        cadastroUsuario.setVisible(true);        
    }//GEN-LAST:event_jMenuItemCadastrarUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton127horas;
    private javax.swing.JButton jButtonAHospedeira;
    private javax.swing.JButton jButtonFastNFurious;
    private javax.swing.JButton jButtonMeuNomeNaoEJhonny;
    private javax.swing.JButton jButtonStarWars;
    private javax.swing.JButton jButtonTheDarkKnight;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabelFilmes;
    private javax.swing.JMenuBar jMenuBarMenuGeral;
    private javax.swing.JMenuItem jMenuItemCadastrarUsuario;
    private javax.swing.JMenuItem jMenuItemMenuPrincipal;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTrocarUsuario;
    private javax.swing.JMenu jMenuMenu;
    private javax.swing.JMenu jMenuRelatorio;
    private javax.swing.JMenu jMenuSair;
    // End of variables declaration//GEN-END:variables
}
